export const FETCH_BEERS_DATA_BEGIN = 'FETCH_BEERS_DATA_BEGIN';
export const FETCH_BEERS_DATA_SUCCESS = 'FETCH_BEERS_DATA_SUCCESS';
export const FETCH_BEERS_DATA_FAILURE = 'FETCH_BEERS_DATA_FAILURE';
